### ISSUE TITLE
Can not steam to vlc

### ISSUE THREAD

**Issue by hamdytest** [primetime43/Xtream-Browser#23]
![image](https://github.com/primetime43/Desktop-IPTV-Browser/assets/166058783/f3775d9f-0856-4b81-a1e9-f7d6e606815b)

**Comment by primetime43** [comment]
@hamdytest does this happen on all channels in your playlist or just certain ones? Does the stream url work in vlc when you copy and open it in vlc manually?

**Comment by hamdytest** [comment]
> @hamdytest does this happen on all channels in your playlist or just certain ones? Does the stream url work in vlc when you copy and open it in vlc manually?

Not all of them
yes it works in vlc
